# Copyright IBM Corp. 2013, 2025
# SPDX-License-Identifier: MPL-2.0

---
- name: hello world
  hosts: 127.0.0.1
  connection: local

  tasks:
    - command: echo {{ pizza_toppings }}
    - debug: msg="{{ pizza_toppings }}"

